import Head from "next/head";
 import { Inter } from "next/font/google";
  import Topbar from "@/components/topbar/topbar";
import NavBar from "@/components/navbar/navbar";
 import 'animate.css';
import Footer from "@/components/footer/footer";
import ActDetail from "@/components/actualites_detail/actualites_detail";
import Breadcumb from "@/components/breadcrumb/breadcumb";
    
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const contact="Société de Batiment, Travaux  Publics et Hydrauliques";
    const image="url('actualites.avif')";
   return (
    <>
      <Head>
      <title>Actualites - Batiment, Travaux Publics et Hydrauliques</title>

      <link rel="icon" href="/logoicon.png" />

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
 
        <script src="https://kit.fontawesome.com/6317faaefd.js" crossorigin="anonymous"></script> 

      </Head>
      <Topbar/>
      <NavBar/>
      <Breadcumb name={contact} image={image}/>
      <ActDetail/>
        <Footer/>
    </>
  );
}
