import Head from "next/head";
 import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
 import Topbar from "@/components/topbar/topbar";
import NavBar from "@/components/navbar/navbar";
 import 'animate.css';
import Footer from "@/components/footer/footer";
 
 import Breadcumb from "@/components/breadcrumb/breadcumb";
import Whyehph from "@/components/whyehph/whyehph";
import Apropos from "@/components/apropos/apropos";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
   const contact="Société de Batiment, Travaux  Publics et Hydrauliques";
  const image="url('contact.png')";
  return (
    <>
      <Head>
      <title>A PROPOS- BTPH</title>

      <link rel="icon" href="/logoicon.png" />

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
 
        <script src="https://kit.fontawesome.com/6317faaefd.js" crossorigin="anonymous"></script> 

      </Head>
      <Topbar/>
      <NavBar/>
   <Breadcumb name={contact} image={image}/>
<Apropos/>

<Whyehph/>

            <div className="container">
                <div className="row p-4 align-items-center justify-content-center">
                    <div className="col-sm-4">
                    <img src="BTPH-personnel.jpeg" className="img-thumbnail"  alt="" srcset="" />
                    </div>
                    <div className="col-sm-8">
                        <h2 className="text-primary">L’esprit d’équipe</h2>
                        <p>Chez BTPH HASNAOUI, l’esprit d’équipe est primordial dans la prise de décision et dans la mise en œuvre de chantier de qualité. La solidarité et la bonne entente des équipes font de l’entreprise un vecteur de performance dans son domaine.</p>
                    </div>
                </div>

            </div>

            <h2 className="text-center text-primary">POURQUOI NOUS CHOISIR ?</h2>
          <center> <hr style={{width: '150px', color:'  rgb(0, 146, 63)' }}/></center> 
            <div className="row">
                <div className="col-sm p-4">
               <div class="d-flex align-items-center p-4 wow fadeIn" data-wow-delay="0.2s">
  <div class="flex-shrink-0">
  <img src="quality.png" width="80" height="80" alt="" srcset="" />
  </div>
  <div class="flex-grow-1 ms-3">
    <h3 className=" ">Qualité Exceptionnelle</h3>
  <p>Nous nous engageons à maintenir des normes de qualité élevées dans tous nos projets, avec la satisfaction du client comme priorité absolue.</p>
  </div>
</div>

            <div class="d-flex align-items-center p-4  wow fadeIn" data-wow-delay="0.4s">
  <div class="flex-shrink-0">
  <img src="save-the-world.png" width="80" height="80" alt="" srcset="" />
  </div>
  <div class="flex-grow-1 ms-3">
  <h3 className=" ">Durabilité Environnementale</h3>
  <p>Nous nous engageons à assurer la sécurité de nos employés, sous-traitants et partenaires avec des protocoles stricts pour zéro accident sur nos chantiers.</p>
   </div>
</div>

<div class="d-flex align-items-center p-4  wow fadeIn" data-wow-delay="0.6s">
  <div class="flex-shrink-0">
  <img src="simplicity.png" width="80" height="80" alt="" srcset="" />
   </div>
  <div class="flex-grow-1 ms-3">
    <h3 className=" ">Intégrité et Éthique</h3>
  <p>L'intégrité est au cœur de notre entreprise, nous traitons nos clients, employés, et partenaires avec respect, honnêteté, et respectons scrupuleusement les lois et réglementations en vigueur.</p>
  </div>
</div>
               </div>
               <div className="col-sm p-4">
               <div class="d-flex align-items-center p-4  wow fadeIn" data-wow-delay="0.3s">
  <div class="flex-shrink-0">
  <img src="shield.png" width="70" height="70" alt="" srcset="" />
 </div>
  <div class="flex-grow-1 ms-3">
    <h3 className=" ">Sécurité Avant Tout</h3>
  <p>Nous nous engageons à assurer la sécurité de nos employés, sous-traitants et partenaires en mettant en place des protocoles stricts pour un environnement de travail sans accident.</p>
  </div>
</div>

            <div class="d-flex align-items-center p-4  wow fadeIn" data-wow-delay="0.5s">
  <div class="flex-shrink-0">
  <img src="public-relation.png" width="80" height="80" alt="" srcset="" />  </div>
  <div class="flex-grow-1 ms-3">
  <h3 className=" ">Engagement Communautaire </h3>
  <p>Nous nous engageons à soutenir les communautés locales à travers des initiatives caritatives et le développement durable.</p>
   </div>
</div>

<div class="d-flex align-items-center p-4  wow fadeIn" data-wow-delay="0.7s">
  <div class="flex-shrink-0">
  <img src="innovation.png" width="80" height="80" alt="" srcset="" />
 </div>
  <div class="flex-grow-1 ms-3">
    <h3 className=" ">Innovation et Excellence</h3>
  <p>
Nous nous engageons à soutenir les communautés locales en participant à des initiatives caritatives et en contribuant au développement durable des régions où nous opérons.</p>
  </div>
</div>
               </div>
            </div>


      <Footer/>
    </>
  );
}
